# Generated by Django 4.0.6 on 2024-04-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='first_Name',
        ),
    ]
