# Generated by Django 4.0.6 on 2024-05-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio1', '0002_mebyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebyme',
            name='aptidoes',
            field=models.CharField(default='Habilidades a serem adicionadas', max_length=500),
        ),
        migrations.AddField(
            model_name='mebyme',
            name='competencias',
            field=models.CharField(default='a serem adicionadas', max_length=500),
        ),
        migrations.AddField(
            model_name='mebyme',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mebyme',
            name='experiencia',
            field=models.CharField(default='a serem adicionadas', max_length=500),
        ),
        migrations.AddField(
            model_name='mebyme',
            name='interesses',
            field=models.CharField(default='Habilidades a serem adicionadas', max_length=1000),
        ),
    ]
