# Generated by Django 4.0.6 on 2024-05-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio1', '0003_mebyme_aptidoes_mebyme_competencias_mebyme_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=2000)),
                ('technologies', models.TextField(max_length=2000)),
                ('django_hands_on_video', models.URLField()),
                ('project_tour_video', models.URLField()),
            ],
        ),
    ]
