# Generated by Django 4.0.6 on 2024-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio1', '0005_allapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebyme',
            name='experiencia',
            field=models.CharField(default='a serem adicionadas', max_length=5000),
        ),
    ]
