# Generated by Django 4.0.6 on 2024-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio1', '0007_handsondjango_visita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handsondjango',
            name='url',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='url',
        ),
        migrations.AddField(
            model_name='handsondjango',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='visita',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
