# Generated by Django 4.0.6 on 2024-04-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacao',
            name='estado',
        ),
    ]
