# Generated by Django 4.0.6 on 2024-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0003_alter_festival_bandas'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='festivais/'),
        ),
    ]
