# Generated by Django 4.0.6 on 2024-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem_Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('disciplina', models.CharField(max_length=50)),
            ],
        ),
    ]
